[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rws-ddlpy"
version = "0.10.1"
maintainers = [
	{ name = "Fedor Baart", email = "fedor.baart@deltares.nl"},
	{ name = "Jelmer Veenstra", email = "jelmer.veenstra@deltares.nl"},
]
description = "Service from Rijkswaterstaat for distributing water quantity data."
readme = "README.md"
keywords = ["ddlpy"]
license = "GPL-3.0"
license-files = ["LICENSE"]
requires-python = ">=3.9"
dependencies = [
	#numpy 2.0 is EOL since June 2026, last version supporting py39
	"numpy>=2.0",
    #pandas>=2.2.2 supports numpy 2: https://github.com/Deltares/dfm_tools/issues/1330
	"pandas>=2.2.2",
    #pandas==2.2.2 depends on python-dateutil>=2.8.2
	"python-dateutil>=2.8.2",
	"pytz",
	"tqdm",
	"click",
	"requests",
]
classifiers = [
	"Development Status :: 3 - Alpha",
	"Intended Audience :: Developers",
	"Intended Audience :: Science/Research",
	"Operating System :: OS Independent",
	"Natural Language :: English",
	"Programming Language :: Python",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: 3.13",
	"Programming Language :: Python :: 3.14",
]

[project.urls]
Home = "https://github.com/deltares/ddlpy"
Code = "https://github.com/deltares/ddlpy"
Issues = "https://github.com/deltares/ddlpy/issues"

[project.optional-dependencies]
dev = [
	"bump2version>=0.5.11",
	"black",
	"pytest>=3.8.2",
	"pytest-cov",
	"twine",
	"build",
	"flake8>=3.5.0",
	"flake8-pyproject", # required to read the config from pyproject.toml
	"tox>=3.5.2",
	"twine>=1.12.1",
]
docs = [
	"sphinx>=1.8.1",
	"sphinx_mdinclude",
	"nbsphinx",
	"pydata-sphinx-theme",
	#"pandoc", # installed with choco on github
]
examples = [
	"jupyter",
	"notebook",
	"matplotlib",
]
netcdf = [
	"xarray>=2024.07.0", # latest release supporting py39
	"scipy",
	"h5netcdf[h5py]",
	"netcdf4",
]

[project.scripts]
ddlpy = "ddlpy.cli:cli"

[tool.setuptools]
packages = ["ddlpy"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--durations=0"
filterwarnings = [
	"error",
	# temporarily ignore numpy incompatibility: https://github.com/Deltares/ddlpy/issues/192
	# this warning broke github tests for python 3.11, 3.12 and 3.13
	"ignore:numpy.ndarray size changed:RuntimeWarning",
    # TODO: ignore numpy warning until it is fixed in netcdf4: https://github.com/Unidata/netcdf4-python/issues/1468
    "ignore:Setting the shape on a NumPy array has been deprecated in NumPy 2.5:DeprecationWarning",
]

[tool.flake8]
exclude = "docs"

## Pixi related entries
[tool.pixi.workspace]
channels  = ["conda-forge"]
platforms = ["linux-64", "win-64"] #, "osx-64", "osx-arm64"]

[tool.pixi.feature.test.tasks]
test = { cmd = ["pytest", "--cov=ddlpy", "--cov-report=xml", "--cov-report=term"] }

[tool.pixi.feature.docs.tasks]
docs-build = { cmd = ["sphinx-build", "docs", "docs/_build"] }

# Install your code in editable mode, dependencies here are installed in all environments
# Takes the dependencies from pyproject.toml, which will be overridden in the features below.
[tool.pixi.pypi-dependencies]
rws-ddlpy = { path = ".", editable = true }

[tool.pixi.feature.minimal.pypi-dependencies]
# the versions are a manual copy of [project.dependencies],
# but with == to test with the lowest versions of direct dependencies
numpy = "==2.0"
pandas = "==2.2.2"
python-dateutil = "==2.8.2"
#pytz = "=="
#tqdm = "=="
#click = "=="
#requests = "=="
# netcdf dependency group
xarray = "==2024.07.0"
#scipy = "=="
#h5netcdf[h5py] = "=="
#netcdf4 = "=="

# Define features for different Python versions and Hydromt versions
[tool.pixi.feature.py39.dependencies]
python = "3.9.*"

[tool.pixi.feature.py310.dependencies]
python = "3.10.*"

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.feature.py313.dependencies]
python = "3.13.*"

[tool.pixi.feature.py314.dependencies]
python = "3.14.*"

[tool.pixi.feature.docs.dependencies]
pandoc = "*"

# Define environments to combine features
[tool.pixi.environments]
default = { features = ["py314", "dev", "docs", "examples", "netcdf", "test"]}

dev = { features = ["py314", "dev"]}

py39 = { features = ["py39", "dev", "test"]}
py310 = { features = ["py310", "dev", "test"]}
py311 = { features = ["py311", "dev", "test"]}
py312 = { features = ["py312", "dev", "test"]}
py313 = { features = ["py313", "dev", "test"]}
py314 = { features = ["py314", "dev", "test"]}

py39-mindeps = { features = ["py39", "dev", "test", "minimal"]}
