name: test-macos

# macos tests are failing with pixi environments, so temporarily adding the working non-pixi tests back
# to be resolved in https://github.com/Deltares/ddlpy/pull/204

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        # we assume it also works for inbetween versions
        python-version: ["3.9", "3.10", "3.12", "3.14"]
        os: [macos-latest]

    name: py-${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev,netcdf]
    - name: list env contents
      run: |
        pip list
    - name: Test with pytest
      run: |
        pytest
